In [84]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import preprocessing

In [85]:
from sklearn import metrics

In [86]:
iris= datasets.load_iris()
x= iris.data
y= iris.target

In [87]:
from sklearn.preprocessing import StandardScaler

In [88]:
scaler= StandardScaler()
x_std= scaler.fit_transform(x)

In [89]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [90]:
x_train, x_test, y_train, y_test= train_test_split(x_std, y, test_size= 0.3, random_state= 1)

In [91]:
x_train.shape

(105, 4)

In [92]:
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


(105,)
(45, 4)
(45,)


# Logistic_Regression

In [93]:
from sklearn.linear_model import LogisticRegression

model= LogisticRegression(random_state=0, multi_class='multinomial', solver='newton-cg')

In [94]:
model.fit(x_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='multinomial',
          n_jobs=None, penalty='l2', random_state=0, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

In [95]:
x_sam= [[.5, .5, .5, .5]]

In [96]:
x_test[1]

array([-0.90068117, -1.28296331, -0.4308277 , -0.13075464])

In [97]:
y_predict= model.predict(x_test)

In [98]:
print(classification_report(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))
print('accuracy:', metrics.accuracy_score(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

   micro avg       0.96      0.96      0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
accuracy: 0.9555555555555556


# Decision_Tree

In [99]:
from sklearn.tree import DecisionTreeClassifier

In [100]:
model_1= DecisionTreeClassifier(criterion='entropy')
model_1.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [101]:
y_predict= model_1.predict(x_test)

In [102]:
print(classification_report(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))
print('accuracy:', metrics.accuracy_score(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

   micro avg       0.96      0.96      0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
accuracy: 0.9555555555555556


In [72]:
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO
from IPython.display import Image
import pydotplus

dot_data= StringIO()
export_graphviz(model_1,
               out_file=dot_data,
               filled=True,
               rounded=True,
               special_characters=True,
               class_names=['0','1','2'])

graph= pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png('iris1.png')
Image(graph.create_png())

# Random_forest

In [103]:
from sklearn.ensemble import RandomForestClassifier

In [106]:
model_2 = RandomForestClassifier(n_estimators=500)
model_2.fit(x_train, y_train)
y_predict= model_2.predict(x_test)

In [107]:
print(classification_report(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))
print('accuracy:', metrics.accuracy_score(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

   micro avg       0.96      0.96      0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
accuracy: 0.9555555555555556


# SVM

In [109]:
from sklearn.svm import SVC

In [111]:
model_3= SVC(gamma='auto')
model_3.fit(x_train, y_train)
y_predict= model_3.predict(x_test)

In [112]:
print(classification_report(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))
print('accuracy:', metrics.accuracy_score(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

   micro avg       0.96      0.96      0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]
accuracy: 0.9555555555555556
