In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [10]:
x= np.array([5, 15, 25, 35, 45, 55]).reshape((-1,1))
y= np.array([5, 20, 14, 32, 22, 38])

In [9]:
x.shape

(6, 1)

In [11]:
y

array([ 5, 20, 14, 32, 22, 38])

In [12]:
model = LinearRegression()

In [13]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
r_sq= model.score(x, y)

In [15]:
print('coeff of det', r_sq)

coeff of det 0.715875613747954


In [17]:
print('intercept0', model.intercept_)


intercept0 5.633333333333329


In [18]:
print('slope', model.coef_)

slope [0.54]


In [19]:
y_pred = model.predict(x)

In [20]:
print('pred reg', y_pred, sep='\n')

pred reg
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [22]:
x_n = np.arange(5).reshape((-1,1))

In [23]:
y_n= model.predict(x_n)

In [25]:
print(y_n)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
